names = ['Carlos', 'Micah', 'William', 'Grace', 'David', 'Alex', 'Emily', 'Derek', 'Jacob', 'Mr. Mckee']
print('1. %s' %(names[0]))
print('2. %s' %(names[1]))
print('3. %s' %(names[2]))
print('4. %s' %(names[3]))
print('5. %s' %(names[4]))
print('6. %s' %(names[5]))
print('7. %s' %(names[6]))
print('8. %s' %(names[7]))
print('9. %s' %(names[8]))
print('10. %s' %(names[9]))