import turtle
def Stop():
    turtle.penup()
    turtle.color('white')
    turtle.pencolor('white')
    turtle.begin_fill()
    turtle.goto(-50 , 200)
    turtle.pendown()
    turtle.backward(50)
    turtle.right(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(10)
    turtle.left(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(60)
    turtle.left(90)
    turtle.forward(40)
    turtle.right(90)
    turtle.forward(35)
    turtle.right(90)
    turtle.forward(40)
    turtle.left(90)
    turtle.forward(10)
    turtle.end_fill()
    turtle.left(90)
def sTop():
    turtle.penup()
    turtle.color('white')
    turtle.pencolor('white')
    turtle.goto(-25 , 200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.backward(50)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(90)
    turtle.right(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(90)
    turtle.left(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(10)
    turtle.end_fill()
    turtle.right(180)
def stOp():
    turtle.penup()
    turtle.color('white')
    turtle.pencolor('white')
    turtle.goto(50 , 190)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(80)
    turtle.right(90)
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(80)
    turtle.penup()
    turtle.goto(40 , 200)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(100)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(100)
def stoP():
    turtle.penup()
    turtle.color('white')
    turtle.pencolor('white')
    turtle.goto(100 , 200)
    turtle.pendown()
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(50)
    turtle.backward(100)
turtle.color('red')
turtle.penup()
turtle.goto(-50 , -50)
turtle.begin_fill()
for x in range(8):
    turtle.pendown()
    turtle.forward(150)
    turtle.left(45)
turtle.end_fill()
Stop()
sTop()
stOp()
stoP()
turtle.exitonclick()